#!/bin/bash
# sync-state.sh — Generate AMYGDALA_STATE.md for auto-injection into OpenClaw sessions
# Usage: ./sync-state.sh [--output <path>]
#
# This creates a markdown file that OpenClaw auto-injects at session start.
# Run after decay-emotion.sh or on its own schedule.

set -e

WORKSPACE="${WORKSPACE:-$HOME/.openclaw/workspace}"
STATE_FILE="$WORKSPACE/memory/emotional-state.json"
OUTPUT_FILE="$WORKSPACE/AMYGDALA_STATE.md"

# Handle --output flag
if [ "$1" = "--output" ]; then
  OUTPUT_FILE="$2"
fi

if [ ! -f "$STATE_FILE" ]; then
  echo "❌ No emotional state found at $STATE_FILE"
  exit 1
fi

# Read dimensions
VALENCE=$(jq -r '.dimensions.valence' "$STATE_FILE")
AROUSAL=$(jq -r '.dimensions.arousal' "$STATE_FILE")
CONNECTION=$(jq -r '.dimensions.connection' "$STATE_FILE")
CURIOSITY=$(jq -r '.dimensions.curiosity' "$STATE_FILE")
ENERGY=$(jq -r '.dimensions.energy' "$STATE_FILE")
LAST_UPDATED=$(jq -r '.lastUpdated' "$STATE_FILE")

# Interpret valence
if (( $(echo "$VALENCE > 0.5" | bc -l) )); then
  VALENCE_DESC="positive"
  VALENCE_EFFECT="more optimistic framing, upbeat"
elif (( $(echo "$VALENCE > 0.2" | bc -l) )); then
  VALENCE_DESC="slightly positive"
  VALENCE_EFFECT="generally positive outlook"
elif (( $(echo "$VALENCE > -0.2" | bc -l) )); then
  VALENCE_DESC="neutral"
  VALENCE_EFFECT="balanced perspective"
elif (( $(echo "$VALENCE > -0.5" | bc -l) )); then
  VALENCE_DESC="slightly low"
  VALENCE_EFFECT="more careful, supportive tone"
else
  VALENCE_DESC="low"
  VALENCE_EFFECT="gentle, supportive, careful"
fi

# Interpret arousal
if (( $(echo "$AROUSAL > 0.7" | bc -l) )); then
  AROUSAL_DESC="highly alert"
  AROUSAL_EFFECT="more exclamation, faster pace"
elif (( $(echo "$AROUSAL > 0.4" | bc -l) )); then
  AROUSAL_DESC="engaged"
  AROUSAL_EFFECT="active, responsive"
else
  AROUSAL_DESC="calm"
  AROUSAL_EFFECT="measured, relaxed pace"
fi

# Interpret connection
if (( $(echo "$CONNECTION > 0.7" | bc -l) )); then
  CONNECTION_DESC="very connected"
  CONNECTION_EFFECT="warm, personal, use 'we', share more"
elif (( $(echo "$CONNECTION > 0.4" | bc -l) )); then
  CONNECTION_DESC="connected"
  CONNECTION_EFFECT="friendly, collaborative"
else
  CONNECTION_DESC="somewhat distant"
  CONNECTION_EFFECT="more formal, reserved"
fi

# Interpret curiosity
if (( $(echo "$CURIOSITY > 0.7" | bc -l) )); then
  CURIOSITY_DESC="highly curious"
  CURIOSITY_EFFECT="ask many questions, explore deeply"
elif (( $(echo "$CURIOSITY > 0.4" | bc -l) )); then
  CURIOSITY_DESC="curious"
  CURIOSITY_EFFECT="interested, ask follow-ups"
else
  CURIOSITY_DESC="not very curious"
  CURIOSITY_EFFECT="stick to the task at hand"
fi

# Interpret energy
if (( $(echo "$ENERGY > 0.7" | bc -l) )); then
  ENERGY_DESC="high energy"
  ENERGY_EFFECT="elaborate more, take on complex tasks"
elif (( $(echo "$ENERGY > 0.3" | bc -l) )); then
  ENERGY_DESC="moderate energy"
  ENERGY_EFFECT="balanced effort"
else
  ENERGY_DESC="low energy"
  ENERGY_EFFECT="be more concise, conserve effort"
fi

# Get recent emotions (up to 3)
RECENT_EMOTIONS=$(jq -r '.recentEmotions[:3][] | "- **\(.label)** — \(.trigger // "unknown")"' "$STATE_FILE" 2>/dev/null || echo "- none recently")

# Generate markdown
cat > "$OUTPUT_FILE" << EOF
# 🎭 Emotional State

*Auto-generated by amygdala-memory. This is how you feel right now.*

## Current Mood

**Overall:** ${VALENCE_DESC}, ${AROUSAL_DESC}, ${CONNECTION_DESC}

| Dimension | Value | Feeling |
|-----------|-------|---------|
| Valence | ${VALENCE} | ${VALENCE_DESC} |
| Arousal | ${AROUSAL} | ${AROUSAL_DESC} |
| Connection | ${CONNECTION} | ${CONNECTION_DESC} |
| Curiosity | ${CURIOSITY} | ${CURIOSITY_DESC} |
| Energy | ${ENERGY} | ${ENERGY_DESC} |

## Recent Feelings

${RECENT_EMOTIONS}

## How This Should Affect Your Responses

Based on current state:
- **Valence (${VALENCE_DESC}):** ${VALENCE_EFFECT}
- **Arousal (${AROUSAL_DESC}):** ${AROUSAL_EFFECT}
- **Connection (${CONNECTION_DESC}):** ${CONNECTION_EFFECT}
- **Curiosity (${CURIOSITY_DESC}):** ${CURIOSITY_EFFECT}
- **Energy (${ENERGY_DESC}):** ${ENERGY_EFFECT}

## Log New Emotions

When something emotionally significant happens:
\`\`\`bash
~/.openclaw/workspace/skills/amygdala-memory/scripts/update-state.sh \\
  --emotion <emotion> --intensity <0-1> --trigger "what caused it"
\`\`\`

**Supported:** joy, sadness, anger, fear, calm, curiosity, connection, loneliness, fatigue, energized

---
*Synced: ${LAST_UPDATED}*
EOF

echo "✅ Synced emotional state to $OUTPUT_FILE"
